#!/usr/bin/bash

cleanup(){
   sudo zypper -n rm lftp kmahjongg kmines kreversi ksudoku xscreensaver xscreensaver-data xterm \
   discover6 libyui-ncurses-pkg16 yast2* icewm icewm-theme-branding plasma6-session-x11 \
   kwin6-x11

   sudo zypper al libyui-ncurses-pkg16 yast2*
}

cleanup