#!/usr/bin/bash

device_test(){
    if [ "$ARG_ONE" == "desktop" ]
    then
        "$HOME"/dsks-tools/test/desktop "$ARG_TWO"
    elif [ "$ARG_ONE" == "laptop" ]
    then
        containers_menu
    else
        echo "Invalid option: $ARG_ONE"
        echo "Only accepts desktop, laptop, minipc or server"
    fi
}