### below is meant to be copy/pasted into .bashrc
# for fedora

grub(){
    sudo grub2-mkconfig -o /etc/grub2.cfg
}


clean(){
    sudo dnf clean all
}

rebuild(){
    sudo akmods --rebuild --force
    sudo dracut --regenerate-all --force
}



### below is meant to be copy/pasted into .bashrc
# for opensuse
grub(){
    sudo grub2-mkconfig -o /etc/grub2.cfg
}


clean(){
    sudo zypper clean
}

rebuild(){
    sudo dracut --regenerate-all --force
}
