### below is meant to be copy/pasted into .bashrc
# for fedora

grub(){
    sudo grub2-mkconfig -o /etc/grub2.cfg
}


clean(){
    sudo dnf clean all
}

rebuild(){
    sudo akmods --rebuild --force
    sudo dracut --regenerate-all --force
}



### below is meant to be copy/pasted into .bashrc
# for opensuse
grub(){
    sudo grub2-mkconfig -o /etc/grub2.cfg
}


clean(){
    sudo zypper clean
}

rebuild(){
    sudo dracut --regenerate-all --force
}

winekill(){
    # https://forum.level1techs.com/t/kill-all-wine-process/186576/6
    pgrep -i '(.*\.(exe|dll|msi|bat|com|lnk)$)|(.*(wine|proton).*))' |xargs -n1 kill -9
}
