#!/usr/bin/bash

rebuild(){
    if [ "$DISTRO" == "fedora" ]
    then
        sudo akmods --rebuild --force
        sudo dracut --regenerate-all --force
    else
        echo "Unsupported distro"
    fi

}

DISTRO=$(source /etc/os-release ; echo $ID)
rebuild