#!/usr/bin/bash

upd(){
    DISCORDLINK="https://discord.com/api/download?platform=linux&format=tar.gz"
    if test -d /opt/apps/Discord; then
        pkill -SIGTERM Discord
        CURRENT_DIR=$(pwd)  #get users current dir before moving to temp
        cd /opt/apps/temp || exit
        curl -L -o discord.tar.gz "$DISCORDLINK"
        tar -xvf discord.tar.gz
        rm -r /opt/apps/Discord
        mv Discord /opt/apps/Discord
        rm discord.tar.gz
        cd "$CURRENT_DIR"  || exit   # go back to the folder user was in when finished
    elif ! test -d /opt/apps/Discord; then
        echo "Discord not downloaded."
    fi
}

upd
