#!/usr/bin/bash

distro_updater(){
    if [ "$DISTRO" == "fedora" ]
    then
        sudo dnf clean all
        sudo dnf update -y
    elif [ "$DISTRO" == "opensuse-tumbleweed" ]
    then
        sudo zypper ref
        sudo zypper -n dup
    elif [ "$DISTRO" == "opensuse-slowroll" ] || [ "$DISTRO" == "opensuse-leap" ]
    then
        sudo zypper ref
        sudo zypper -n up
    else
        echo "Unsupported distro"
    fi

}

update_rclone(){    
    if test -f /usr/bin/rclone; then
        sudo -v ; curl https://rclone.org/install.sh | sudo bash
    elif ! test -f /usr/bin/rclone; then
        echo "Rclone not installed."
    fi
}

update_discord(){
    DISCORDLINK="https://discord.com/api/download?platform=linux&format=tar.gz"
    if test -d /opt/apps/Discord; then
        pkill -SIGTERM Discord
        mkdir /opt/apps/temp
        cd /opt/apps/temp || exit
        curl -L -o discord.tar.gz "$DISCORDLINK"
        tar -xvf discord.tar.gz
        rm -r /opt/apps/Discord
        mv Discord /opt/apps/Discord
        rm discord.tar.gz
        nohup /opt/apps/Discord/Discord > /dev/null 2>&1 &
        rm /opt/apps/temp/nohup.out
    elif ! test -d /opt/apps/Discord; then
        echo "Discord not downloaded."
    fi
}

DISTRO=$(source /etc/os-release ; echo $ID)
flatpak update -y
flatpak remove --unused -y  
update_rclone
update_discord
distro_updater