#!/usr/bin/bash

distro_updater(){
    if [ "$DISTRO" == "fedora" ]
    then
        sudo dnf clean all
        sudo dnf update -y
    elif [ "$DISTRO" == "opensuse-tumbleweed" ]
    then
        sudo zypper ref
        sudo zypper -n dup
    elif [ "$DISTRO" == "opensuse-slowroll" ] || [ "$DISTRO" == "opensuse-leap" ]
    then
        sudo zypper ref
        sudo zypper -n up
    else
        echo "Unsupported distro"
    fi

}

update_rclone(){    
    if test -f /usr/bin/rclone; then
        sudo -v ; curl https://rclone.org/install.sh | sudo bash
    elif ! test -f /usr/bin/rclone; then
        echo "Rclone not installed."
    fi
}

DISTRO=$(source /etc/os-release ; echo $ID)
flatpak update -y
flatpak remove --unused -y  
update_rclone
distro_updater